//variaveis

//funcoes



criarCartao(
    'Programação'
    'Oque é JavaSript ??'
    'o JavaScript é uma lingugem de programação'

)criaCartao(
    'Programação',
    'O que é Python?',
    'O Python é uma linguagem de programação'
)

criaCartao(
    'Geografia',
    'Qual a capital da França?',
    'A capital da França é Paris'
)

criaCartao(
    'Programação',
    'O que é uma função?',
    'Uma função é um bloco de código que executa alguma tarefa'
)

criaCartao(
    'Música'
    'Qual a minha futura profissão?'
    'Cantor'
)
